#!/bin/bash

trap 'exit 0' SIGTERM


# ssh magic
mkdir /mishell/ssh
if [ ! -f /mishell/ssh/id_rsa ]; then
	ssh-keygen -t rsa -N "" -f /mishell/ssh/id_rsa
fi

if [ ! -f /mishell/ssh/known_hosts ]; then
	IFS=', ' read -r -a array <<< "$KNOWN_HOSTS"
	for element in "${array[@]}"
	do
		ssh-keyscan -t rsa $element >> /mishell/ssh/known_hosts
	done
fi
#chmod -R 700 /root/.ssh/id_rsa

# create users
IFS=', ' read -r -a array <<< "$USERS"
for element in "${array[@]}"
do
	IFS=':' read username uid <<< "$element"
	useradd -m -u $uid $username
	mkhomedir_helper $username
	homedir=$( getent passwd "$username" | cut -d: -f6 )
	cp -r /mishell/ssh/ "$homedir"/.ssh
	chown -R $username:$username $homedir
	chmod -R 700 $homedir
done



#   sudo -u www-data git fetch origin testDeploy-two



echo "date.timezone=${TIMEZONE};"  >> ${PHP_INI_DIR}/conf.d/custom.ini


php	/mishell.phar profiles sudo daemon \
|	tee -a /mishell/log/general.log
